### PR TITLE
Kyle/implement mint

### PR DESCRIPTION
**Pull request by knoll3**
# Nucleus Integration
Implements Nucleus minting in Eclipse.

[Nucleus](https://www.nucleusearn.io/) provides the ability to mint and bridge tETH to the Eclipse network using one of our accepted assets. This PR provides that functionality directly into the Eclipse UI through a new page on the Eclipse app. 
image

### Notes 
- New route called `/mint` was created. This should be changed to whatever it needs to be. 
- On the Figma design there is a nav bar on the left that doesn't exist on prod. I was told this is currently being developed by the Eclipse team. The new `/mint` route will need to be added to that nav bar when it is complete.
- All code changes are in the `mint` directory under `app/mint`.
- Some new assets have been added to the public folder. 
- You will notice some changes in the diff outside of the mint directory, but these are just new lines and empty spaces caused by prettier. 
- The `Mint.tsx` component is one big component for simplicity. It could easily be broken down into smaller pieces. 
- Implemented the mint page based on the figma provided below
- Implemented the transaction modal based on the production transaction modal
- I used a new "mint" version of the transaction modal since I wanted to implement a simpler version that is not tied to any context or backend api.

### Testing
Note that testing only works on mainnet for now. Our contracts are deployed on Tenderly but I was having trouble getting Dynamic to connect to Tenderly. So testing will have to be done on mainnet.

1. Ensure your wallet has a balance in one of our accepted assets: ezETH, apxETH, rswETH, weETH, or WETH
2. Navigate to http://localhost:3000/mint
3. Select the token asset you want to deposit
4. Enter a deposit amount into the input box 
5. Click "Mint"
6. You will be prompted to approve the contract to use your tokens
7. If your wallet prompts you to sign the deposit message, this means that simulate passed so you can feel pretty confident that the transaction will work. You can reject the transaction at this point if you don't want to pay gas fees.
8. If you want to follow through and pay gas fees, then you can do so and verify that the transaction modal shows the correct information. 
  
### Figma
- https://www.figma.com/design/9h3HDcACU0JleBUKmduR7d/Eclipse-%3C%3E-Nucleus?node-id=1-274&node-type=frame&t=52sKp3H2msnV4ocf-11

### More Screenshots
Amount over balance
image
Deposit pending
image
Deposit complete
image

### CODE REVIEW

**Comment by hkey0** [comment]
Hey, thanks for the pr. There are a few things I noticed:

- If my balance is zero, it looks like that. We can show - or 0 or 0.00
resim
- a few components/features seem to be missing. ($ value of the token, percentage buttons, eth/teth rate, time and cost component). Will you add these?
- there's a gap at the bottom of the page (firefox & brave):
resim

**Comment by knoll3** [comment]
> Hey, thanks for the pr. There are a few things I noticed:
> 
> * If my balance is zero, it looks like that. We can show - or 0 or 0.00
>   resim
> * a few components/features seem to be missing. ($ value of the token, percentage buttons, eth/teth rate, time and cost component). Will you add these?
> * there's a gap at the bottom of the page (firefox & brave):
>   resim

1. Fixed the empty balance issue, it now shows "0.00"
2. Not every UI element was planned for this release. We decided to focus on the critical elements first then finish it up later on. 
3. Fixed the issue where white space was appearing at the bottom. 
4. Also hooked the page up to the nav bar on the left.

**Comment by hkey0** [comment]
hello again, thanks for your work. there are a few more bugs, then we're ready!

1) button must be disabled if the user enters 0 in the input
resim

2) If the user has not connected their wallet, we change the button to a "connect wallet" button. 
resim
here is an example (in the bridge page):
resim
https://github.com/Eclipse-Laboratories-Inc/eclipse-bridge-ux/blob/eclipse-apps/app/components/Deposit/DepositContent.tsx#L216

3) "Depositing" box looks a little bigger
resim

**Comment by hkey0** [comment]
thanks

**Pull request merged**
